First release for X-NUCLEO-IKS02A1-Audio
stm32duino/X-NUCLEO-IKS02A1-Audio pull request #1
Opened 2020-12-16 15:33 UTC by sarachiodo

2020-12-16 17:05 UTC, fpistm requested changes
I did not review the source code only the library info.

2020-12-16 17:05 UTC, fpistm commented on README.md
> +Arduino library to support the  IMP34DT05 digital microphone
```suggestion
Arduino library to support the [IMP34DT05](https://www.st.com/en/mems-and-sensors/imp34dt05.html) digital microphone.
```

2020-12-16 17:05 UTC, fpistm commented on README.md
> +Up to version 2.0 it is necessary to apply the following steps:
```suggestion
Up to [STM32 core](https://github.com/stm32duino/Arduino_Core_STM32) version 2.0.0 it is necessary to apply the following steps:
```

2020-12-16 17:05 UTC, fpistm commented on README.md
> +Check the path of folder where the file preferences.txt are in Arduino IDE -> Preferences.
```suggestion
Check the where the Arduino `preferences.txt` file are in `Arduino IDE -> Preferences`.
```

2020-12-16 17:05 UTC, fpistm commented on README.md
> +	For Example: C:\Users\Duino\AppData\Local\Arduino15
```suggestion
	For Example: `C:\Users\Duino\AppData\Local\Arduino15` (Windows)
```

2020-12-16 17:05 UTC, fpistm commented on README.md
> +Then go to ..\packages\STM32\hardware\stm32\NRversion\cores\arduino\stm32\stm32yyxx_half_conf.h and open the file.
```suggestion
Then go to `..\packages\STM32\hardware\stm32\<release version>\cores\arduino\stm32\stm32yyxx_half_conf.h` and open the file.
```

2020-12-16 17:05 UTC, fpistm commented on README.md
> +	#endif
```suggestion
```C
	#if !defined(HAL_I2S_MODULE_DISABLED)
  		#define HAL_I2S_MODULE_ENABLED
	#else
	  #undef HAL_I2S_MODULE_ENABLED
	#endif

	#if !defined(HAL_SAI_MODULE_DISABLED)
	  #define HAL_SAI_MODULE_ENABLED
	#else
	  #undef HAL_SAI_MODULE_ENABLED
	#endif
\``` 
```
Remove the \, as I don't know how to protect them inside GH suggestion 😉

2020-12-16 17:05 UTC, fpistm commented on README.md
> +This library acquire PDM, convert PDM to PCM and store the data on SD Card as WAVE file.
```suggestion
This library acquires PDM, convert PDM to PCM and store the data on SD Card as WAVE file.
```

2020-12-16 17:05 UTC, fpistm commented on README.md
> +	PDM.begin();
```suggestion
`	PDM.begin();`
```

2020-12-16 17:05 UTC, fpistm commented on README.md
> +	PDM.onReceive(foo);
```suggestion
Thanks  the `PDM` instance, it is possible to start to acquire the data, stop, pause the acquisition and resume.

- Start to acquire the PDM data:
	
`	PDM.Record(buffer);`

- Stop to acquire the PDM data:
	
`	PDM.Stop();`

- Pause the acquisition:
	
`	PDM.Pause();`

- Resume the acquisition.
	
`		PDM.Resume();`

- To perform a function to process the data (foo in the example), it can call the function below:
	
`		PDM.onReceive(foo);`
```

2020-12-16 17:05 UTC, fpistm commented on README.md
> +	pdm2pcm_init();
```suggestion
`	pdm2pcm_init();`
```

2020-12-16 17:05 UTC, fpistm commented on README.md
> +	pdm2pcm(BufIn, BufOut, BLOCK_SIZE);
```suggestion
```C++
	pdm2pcm_volume(volume);
	

	pdm2pcm(BufIn, BufOut, BLOCK_SIZE);
\```
```

2020-12-16 17:05 UTC, fpistm commented on keywords.txt
> +PDM_ERROR	LITERAL1
Referring to Arduino library specification:
https://arduino.github.io/arduino-cli/latest/library-specification/#keywordstxt-format

> keywords.txt is formatted in four fields which are separated by a single true tab (not spaces):

Is seems there are more than one tab.

2020-12-17 09:21 UTC, cparata requested changes

2020-12-17 09:21 UTC, cparata commented on src/PDM.h
> +    virtual void DMAHalfCpltCallback(void);
Hi @sarachiodo ,
I guess we can remove virtual keyword from DMAHalfCpltCallback.
Best Regards,
Carlo

2020-12-17 09:21 UTC, cparata commented on src/PDM.h
> +    virtual void DMACpltCallback(void);
Hi @sarachiodo ,
I guess we can remove virtual keyword from DMACpltCallback.
Best Regards,
Carlo

2020-12-17 09:57 UTC, cparata requested changes

2020-12-17 09:57 UTC, cparata commented on README.md
> +Then go to `..\packages\STM32\hardware\stm32\<release version>\cores\arduino\stm32\stm32yyxx_half_conf.h` and open the file.
stm32yyxx_half_conf.h should be stm32yyxx_hal_conf.h

2020-12-17 09:57 UTC, cparata commented on library.properties
> +architectures=stm32
missing the new line at the end of the file

2020-12-17 10:15 UTC, cparata requested changes

2020-12-17 10:15 UTC, cparata commented on src/pdm_low_level_f401re.cpp
> +  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
Hi @sarachiodo ,
I noticed that the Arduino compiler gives a warning. We need to replace {0} with simply {}

2020-12-17 10:15 UTC, cparata commented on src/pdm_low_level_f401re.cpp
> +  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
Hi @sarachiodo ,
I noticed that the Arduino compiler gives a warning. We need to replace {0} with simply {}

2020-12-17 10:15 UTC, cparata commented on src/pdm_low_level_f401re.cpp
> +  RCC_PeriphCLKInitTypeDef PeriphClkInitStruct = {0};
Hi @sarachiodo ,
I noticed that the Arduino compiler gives a warning. We need to replace {0} with simply {}

2020-12-17 10:15 UTC, cparata commented on src/pdm_low_level_f401re.cpp
> +  GPIO_InitTypeDef GPIO_InitStruct = {0};
Hi @sarachiodo ,
I noticed that the Arduino compiler gives a warning. We need to replace {0} with simply {}

2020-12-17 10:15 UTC, cparata commented on src/pdm_low_level_l476rg.cpp
> +  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
Hi @sarachiodo ,
I noticed that the Arduino compiler gives a warning. We need to replace {0} with simply {}

2020-12-17 10:15 UTC, cparata commented on src/pdm_low_level_l476rg.cpp
> +  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
Hi @sarachiodo ,
I noticed that the Arduino compiler gives a warning. We need to replace {0} with simply {}

2020-12-17 10:15 UTC, cparata commented on src/pdm_low_level_l476rg.cpp
> +  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};
Hi @sarachiodo ,
I noticed that the Arduino compiler gives a warning. We need to replace {0} with simply {}

2020-12-17 10:15 UTC, cparata commented on src/pdm_low_level_l476rg.cpp
> +  GPIO_InitTypeDef GPIO_InitStruct;
Hi @sarachiodo ,
I noticed that GPIO_InitStruct is not initialized, I would initialize it in this way:

GPIO_InitTypeDef GPIO_InitStruct = {};

2020-12-17 10:26 UTC, cparata approved these changes

2020-12-17 11:08 UTC, fpistm requested changes

2020-12-17 11:08 UTC, fpistm commented on README.md
> +Check the where the Arduino `preferences.txt` file are in `Arduino IDE -> Preferences`.
```suggestion
Check where the Arduino `preferences.txt` file are in `Arduino IDE -> Preferences`.
```

2020-12-17 11:08 UTC, fpistm commented on README.md
> +In the file add this line of code:
```suggestion
In the file add these lines of code:
```

2020-12-17 11:08 UTC, fpistm commented on README.md
> +This library acquires PDM, convert PDM to PCM and store the data on SD Card as WAVE file.
```suggestion
This library acquires PDM, converts PDM to PCM and stores the data on SD Card as WAVE file.
```

2020-12-17 11:08 UTC, fpistm commented on README.md
> +Before acquire PDM it is required to inizialized it:
```suggestion
Before acquire PDM it is required to initialized it:
```

2020-12-17 11:08 UTC, fpistm commented on README.md
> +Thanks  the `PDM` instance, it is possible to start to acquire the data, stop, pause the acquisition and resume.
```suggestion
Thanks to the `PDM` instance, it is possible to start to acquire the data, stop, pause the acquisition and resume.
```

2020-12-17 11:08 UTC, fpistm commented on keywords.txt
> +PDM_ERROR	LITERAL1
Review this file carefully. As stated before it must be 1 tab not space or more tabs. Several line does not match this rules.

2020-12-17 11:49 UTC, cparata requested changes

2020-12-17 11:49 UTC, cparata commented on README.md
> +This library acquires PDM, converts PDM to PCM and stores the data on SD Card as WAVE file.
Hi @sarachiodo ,
actually the SD card and wave stuff have been moved on the FP_Examples, so we can say only:

This library acquires PDM and converts PDM to PCM

2020-12-17 12:38 UTC, fpistm commented on README.md
> +Before acquire PDM it is required to initialized it:
```suggestion
Before acquire PDM it is required to initialize it:
```

2020-12-17 12:38 UTC, fpistm approved these changes

2020-12-17 12:39 UTC, fpistm commented
OK for me. I've fix a small typo in the README.md so created a second commit. Think to squash and merge instead of Merge pull request.

2020-12-17 12:40 UTC, cparata approved these changes

2020-12-17 12:40 UTC, merged